name: Socket CI/CD - Deploy to AWS S3

on:
  push:
    branches:
      - main
      - develop # 테스트

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: AWS Credentials 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: React 빌드
        run: |
          npm install
          npm run build

      - name: 빌드한 파일을 S3에 업로드
        run: aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
